apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mqio19mfx-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-java-springboot:0562cf96477d05d992d066c00f1725ccc10fa4ae@sha256:4a523d19c9da8c6848750d9a73289440d0e6d4042b34092f13405f13ae1c6a4d
          name: container-image
